### ISSUE TITLE
(Suggestion)Allow scaling config?

### ISSUE THREAD

**Issue by TKDancer** [pheonix99/PhoenixsCantrips#2]
as jankly implemented as the old scaling cantrip mod was, it did offer the ability to edit the scaling rules of the cantrips, any chance that could be implemented in this mod? or was the ability config the spells what caused the junk data?

**Comment by pheonix99** [comment]
I'm basically retired from WotR modding apart from maintaining compatibility. 

It's unlikely to happen.

Shouldn't be the cause of the junk data, tho.

**Comment by TKDancer** [comment]
sad to hear, godspeed
